library(ggplot2)
png(filename = "plot3-POINT.png", width = 480, height = 480)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
qplot(year,Emissions,data = NEI[which(NEI$fips == 24510 & NEI$type == "POINT"),], main = "POINT")
#xyplot(Emissions ~ year | type,data = NEI,layout = c(4,1))
dev.off()
png(filename = "plot3-NONPOINT.png", width = 480, height = 480)
qplot(year,Emissions,data = NEI[which(NEI$fips == 24510 & NEI$type == "NONPOINT"),], main = "NONPOINT")
dev.off()
png(filename = "plot3-ON-ROAD.png", width = 480, height = 480)
qplot(year,Emissions,data = NEI[which(NEI$fips == 24510 & NEI$type == "ON-ROAD"),], main = "ON-ROAD")
dev.off()
png(filename = "plot3-NON-ROAD.png", width = 480, height = 480)
qplot(year,Emissions,data = NEI[which(NEI$type == "NON-ROAD" & NEI$fips == 24510),], main = "NON-ROAD")
dev.off()